orx-no-clear/README.md, orx-no-clear/src/main/kotlin/NoClear.kt
This is a enhancement to the `NoClear()` extension. This feature suppports the drawing of a custom backdrop if it is provided as a codeblock. 
This is a somewhat 'cleaner' alternative to managing the backdrop in the draw() loop.
_It is optional. The current functioning is not impacted._ 
- use of lambda parameter 
- introduces the potential for issues with scope, visibility, etc 
- the onus is on coder to ensure lambda code is valid for this (RenderTarget) context.
- the intended use is quite simple as illustrated by the examples, but the coder could increase the complexity (leading to un-envisaged problems?).
- size events and associated 'scaling' is still the coder's responsibility.
- async loaded images may not yet be available on the first invocation.  Its kinda problematic because …
=> NoCLear() extension : provide a custom backdrop

orx-noise/src/main/kotlin/Distribute.kt, orx-noise/src/main/kotlin/Random.kt, orx-noise/src/main/kotlin/UniformRandom.kt
The `Random` singleton class is an alternative to the individual import of noise/random functions. It helps managing the whole randomisation process by abstracting the seed handling and making sure it's the same throughout the whole project, while also allowing easier iterating by changing the seed in one place.
I've also added some new stuff such as:
* `pick` - gets one or more non-repeating elements from a collection
* `gaussian` - Gaussian distribution
* `pareto` - Pareto distribution
* `roll` - Picks an element from a collection based on decreasing or increasing probabilities
I've also incorporated what I thought to be useful methods from Kotlin's Random package.
If/when this is okay, I'll updated docs/guide
=> Add Random singleton to orx-noise

orx-camera/src/main/kotlin/AxisHelper.kt, orx-camera/src/main/kotlin/GridHelper.kt
+ Rename Debug3D to GridHelper
Would be an interest in adding the `getRotation` function to `Matrix44`? Could also add a method to extract the translation and scale matrices.
=> Add AxisHelper to orx-camera

orx-osc/src/main/kotlin/OSC.kt
```kotlin
val params = object {
var track1: Double = 0.0
var track2: Double = 0.0
}
osc.listen {
"/track1" bind params::track1
"/track2" bind params::track2
}
```
Makes it easier to handle single events. Unfortunately, Generics is not my strong suit so I just created a method for Double which tends to be the most used type in our applications.
=> Add 1 parameter binding to OSC

orx-palette/src/main/kotlin/PaletteStudio.kt
* `onChange` listener - it's useful to know when the palette has changed (f.ex: redraw shapes)
* `add` - a method to add a new palette to the current collection
=> Add onChange listener and addPalette method to orx-palette

orx-shade-styles/src/main/kotlin/LinearGradient.kt
Add pow exponent to linear gradient. 
A high exponent pushes colors towards the first color in the gradient.
The default 1.0 value produces the previous linear result.
=> Add LinearGradient exponent

orx-noise/src/main/kotlin/Random.kt
`Random.bool()` returned true with 50% probability.
Now you can specify your chances:
`Random.bool(0.01)` is a rare event, `Random.bool(0.99)` almost certain.
=> Add probability to Random.bool()

orx-gui/src/main/kotlin/Gui.kt
gui was intercepting mouse events (and reacting to them) while invisible. 
copies the use of "collapsed" from below in the same file.
=> Fix #74 gui blocking mouse events while hidden

orx-gui/src/demo/kotlin/DemoOptions01.kt, orx-gui/src/demo/kotlin/DemoSimple01.kt
Do not collapse the guis so the demo screenshots show what's going on.
Do other changes for more understandable screenshots.
=> Tweak orx-gui demos to produce better screenshots

orx-panel/src/demo/kotlin/DemoHorizontalLayout01.kt, orx-panel/src/main/kotlin/org/openrndr/panel/elements/TextElements.kt
With this change, if a `Button` changes its own `label` on click, or if a `Button` changes another `TextElement` like an `h1` on click, it updates immediately without having to call `requestDraw()` manually.
=> [orx-panel] trigger requestDraw when changing TextElement text

README.md, build.gradle
Was missing the headline/body separator.
Also add non breaking spaces to not wrap orx- names
=> Fix readme table

orx-fx/src/main/kotlin/color/ColorCorrection.kt, orx-fx/src/main/resources/org/openrndr/extra/fx/gl3/color/color-correction.frag
Without this the filter can return negative or too high values (with floating point buffers) which can lead to unexpected results (like darker results with blend mode Add).
=> Make ColorCorrection clamped by default, add Boolean setting

.github/workflows/generate-screenshots.yml, README.md, build.gradle, orx-chataigne/README.md
The change to orx-chataigne readme is only to make it look better in the main README.md file.
=> Enable automatic README generation

README.md, build.gradle
Otherwise when you click in the link you can't see the src/
or other files in the orx while in GitHub.
In branch master because otherwise I couldn't test the action.
=> Link entries in README to folders/ not README.md

orx-boofcv/src/demo/kotlin/DemoSimplified01.kt
Better for usage in plotters. Otherwise straight lines
are made of hundreds of tiny stair-cased points.
=> Add BoofCV demo greatly reducing point counts.

openrndr-demos/src/demo/kotlin/DemoContourIntersections01.kt, openrndr-demos/src/demo/kotlin/DemoContourIntersections02.kt, openrndr-demos/src/demo/kotlin/DemoContourIntersections03.kt
1. Change size of circles indicating intersections
to make it obvious that the circles are not filled,
and that only part of the intersecting shapes are
being drawn.
2. Make intersecting shapes more visible by using
different colors. More fun interaction.
3. Animate self-intersecting shape.
=> Tweak contour intersection demos

openrndr-demos/src/demo/kotlin/DrawerNegativeDimensions.kt
The correct rendering of strokes in this demo depends on https://github.com/openrndr/openrndr/pull/154
=> Add Demo rendering shape strokes with negative dimensions

orx-video-profiles/src/main/kotlin/GIFProfile.kt
Fixes the below phenomenon of the y-axis being flipped when using the GIFProfile
=> Add vflip argument to GIFProfile

orx-chataigne/src/main/kotlin/ChataigneOSC.kt
The casting of the OSC array to a color fails.
Taking a look at `it` with the debugger reveals
Its my first time writing Kotlin and its not pretty code for sure but it fixes the bug - I am glad about any code review here!
=> Fix ColorChannel in Chataigne

orx-temporal-blur/src/main/kotlin/TemporalBlur.kt
Setting `jitter` to 0 didn't work before because `Vector2.uniformRing` then tries to generate a number with squared norm strictly less than 0, and gets struck in an infinite loop.
Another small issue I found was that  `samples - 1` different timestamps were used and one was rendered twice. For illustration:
Before:
After:
=> TemporalBlur: allow 0 jitter and fix small bug

orx-shapes/src/main/kotlin/RegularStar.kt
The `phase` parameter was not used when creating a `regularStar`. It was correctly used for the rounded and beveled versions, I copied the idea from there and added it also to `regularStar`
=> [orx-shapes] use phase parameter in regularStar

orx-shapes/src/demo/kotlin/DemoBezierPatch01.kt, orx-shapes/src/demo/kotlin/DemoBezierPatch02.kt, orx-shapes/src/demo/kotlin/DemoBezierPatch03.kt, orx-shapes/src/demo/kotlin/DemoBezierPatch04.kt
- Remove redundant code.
- Move code out of `extend`.
- New look of DemoBezierPatch01:
Previously the top-left quarter of the mesh was red, looking like a masked area. I displaced it to make it more obvious that it is a sub patch and I added visible "patch control segments".
=> Add comments to bezierPatch demos, simplify.

orx-compositor/src/commonMain/kotlin/Compositor.kt
Similar problem as in orx-panel (https://github.com/openrndr/orx/commit/ba4db38441ee881bd9033ea4dcf33d8112714e50)
=> Fix 0x0 render target creation in compositor

build.gradle
Links for jvm orx'es were broken. Fixed.
Also orx'es are now shown in two lists: multiplatform and jvm.
=> Fix readme generator (multiplatform / jvm)

orx-shapes/src/commonMain/kotlin/BezierPatch3D.kt, orx-shapes/src/commonMain/kotlin/drawers/BezierPatchDrawer.kt, orx-shapes/src/demo/kotlin/DemoBezierPatch05.kt
Adds `BezierPatch3DBase<C>` and `BezierPatch3D`. These are 3D versions of `BezierPatchBase<C>` and `BezierPatch`, with:
- `Vector2` -> `Vector3`
- `Segment` -> `Segment3D`
- `ShapeContour` -> `Path3D`
Adds functions to `BezierPatchDrawer` for drawing `BezierPatch3DBase<C>`
Adds a demo: `DemoBezierPatch05.kt`
Notes:
- Currently, the `bezierPatch` function is overloaded for making 3D Bézier patches; this seemed nicest to me, but changing it to `bezierPatch3D` is also an option.
- ~The demo screenshotter has no multisample currently, so the screenshot may look aliased.~ (changed in last commit)
- For me the function `bezierPatches` for drawing multiple Bézier surfaces at once gave an error, but I haven't looked further into the problem. I draw a list of Bézier patches `bps` now by …
=> Add 3D Bézier patch

orx-jvm/orx-git-archiver/src/main/kotlin/NativeGit.kt
Small fix for #193. The commit hash of NativeGit has a newline at the end.. I didn't notice it during testing, but orx-gui can't handle the newline which is how it came to my attention
=> [orx-git-archiver] Remove trailing whitespace in commit hash

orx-palette/src/main/kotlin/PaletteStudio.kt
`getLuminance()` returns a normalized Double. 
The comparator used the difference of two normalized luminances and converted the result `.toInt()` which gave `0` in most cases, which did not sort the colors as expected.
=> Fix PaletteStudio color sorting

orx-fx/src/commonMain/kotlin/color/Invert.kt, orx-fx/src/shaders/glsl/color/invert.frag
To make it convenient to invert a colorBuffer when applying a series of filters.
Invert exists as a filter in CSS.
=> Add Invert fx filter

orx-jumpflood/src/demo/kotlin/DemoShapeSDF01.kt, orx-jumpflood/src/demo/kotlin/DemoShapeSDF02.kt, orx-jumpflood/src/demo/kotlin/DemoShapeSDF03.kt, orx-jumpflood/src/demo/kotlin/DemoShapeSDF04.kt, orx-jumpflood/src/demo/kotlin/DemoShapeSDF05.kt, orx-jumpflood/src/demo/kotlin/DemoSkeleton01.kt, orx-jumpflood/src/main/resources/shaders/gl3/alpha-threshold.frag, orx-jumpflood/src/main/resources/shaders/gl3/contour-points.frag, orx-jumpflood/src/main/resources/shaders/gl3/draw/sdf-stroke-fill.frag, orx-jumpflood/src/main/resources/shaders/gl3/encode-points.frag, orx-jumpflood/src/main/resources/shaders/gl3/encode-subpixel.frag, orx-jumpflood/src/main/resources/shaders/gl3/fx/inner-bevel.frag, orx-jumpflood/src/main/resources/shaders/gl3/fx/inner-glow.frag, orx-jumpflood/src/main/resources/shaders/gl3/fx/inpaint.frag, orx-jumpflood/src/main/resources/shaders/gl3/fx/outer-glow.frag, orx-jumpflood/src/main/resources/shaders/gl3/fx/skeleton.frag, orx-jumpflood/src/main/resources/shaders/gl3/fx/straight-skeleton.frag, orx-jumpflood/src/main/resources/shaders/gl3/jumpflood.frag, orx-jumpflood/src/main/resources/shaders/gl3/ops/sdf-blend.frag, orx-jumpflood/src/main/resources/shaders/gl3/ops/sdf-onion.frag, orx-jumpflood/src/main/resources/shaders/gl3/ops/sdf-round.frag, orx-jumpflood/src/main/resources/shaders/gl3/ops/sdf-smooth-difference.frag, orx-jumpflood/src/main/resources/shaders/gl3/ops/sdf-smooth-intersection.frag, orx-jumpflood/src/main/resources/shaders/gl3/ops/sdf-smooth-union.frag, orx-jumpflood/src/main/resources/shaders/gl3/pixel-direction.frag, orx-jumpflood/src/main/resources/shaders/gl3/pixel-distance.frag, orx-jumpflood/src/main/resources/shaders/gl3/shape-sdf.frag, orx-jumpflood/src/main/resources/shaders/gl3/threshold.frag
To make it convenient to invert a colorBuffer when applying a series of filters.
Invert exists as a filter in CSS.
=> Remove version from jumpflood

orx-mesh-generators/src/main/kotlin/Plane.kt
Add method to convert a Rectangle object into a vertexBuffer representing that Rectangle. 
The resolution (in pixels) can be customized and it defines the number of columns and rows to create.
=> Add Rectangle.toMesh()

orx-quadtree/src/commonMain/kotlin/IQuadtree.kt, orx-quadtree/src/commonMain/kotlin/Quadtree.kt, orx-quadtree/src/jvmMain/kotlin/ReadwriteQuadtree.kt
Sometimes you want to ask for objects near a point that is not itself associated with the generic object type
@ricardomatias is there a better way to structure this?  the code is identical  to nearest(...) except for the element === obj comparison
=> quadtree enhancements -- nearestToPoint, and Readwrite locking

.github/workflows/generate-screenshots.yml
This took 3 days to figure out.
It involved creating an Ubuntu 20.04 virtualbox,
compiling and modifying multiple times the latest Mesa,
packaging and uploading it as a tar.gz to openrndr/setup-opengl,
tweaks and debugging suggested by Edwin until discovering that
skipping the openSWR renderer altogether seems
to solve the issue.
=> Make screenshot generation work again

orx-shapes/src/commonMain/kotlin/HobbyCurve.kt
The blue ShapeContour is converted to the red one using `myBlueCurve.hobbyCurve()`
Before this fix the resulting curve ends too early:
After the fix the resulting curve shares start and end points with the original curve and passes through all the same control points:
=> Hobby curves: add last point for open contours

orx-camera/README.md
Replace Debug3D (no longer exists) with AxisHelper and GridHelper
Remove shadeStyle and perspective()
Add imports
Add cube, sphere, repeated circles and comments
=> Fix orx-camera readme

orx-no-clear/src/commonMain/kotlin/NoClear.kt
Currently orx-noclear creates somewhat blurry results on hi-dpi screens. I noticed the problem is resolved when contentScale is passed along in the renderTarget.
=> Add contentScale to orx-noclear's renderTarget creation

orx-compositor/src/commonMain/kotlin/Compositor.kt, orx-compositor/src/demo/kotlin/DemoCompositor02.kt
Continuation of Yvee1's work in #204 to address #178.
I need more test cases to verify it works for all cases but it seems to handle the basic composite layers fine.
Also makes layers contentScale aware.
=> [orx-compositor] BufferMultisample in Layer 

.github/workflows/build.yml, .github/workflows/generate-screenshots.yml, .github/workflows/release-candidate-to-maven-central.yml, .github/workflows/release-to-maven-central.yml
Change build action to run on pull requests.
Include collectScreenshots tasks into build action.
Bring generate-screenshots in line with build changes.
Update versions and use descriptive names for jobs.
=> Fix build action

orx-shapes/src/commonMain/kotlin/RectangleGrid.kt
With certain margin values one would get a column or row too few.
=> Fix Rectangle.grid rounding error

orx-jvm/orx-midi/src/main/kotlin/MidiEvent.kt, orx-jvm/orx-midi/src/main/kotlin/MidiTransceiver.kt
Make pitch bend values match `midisnoop` values.
Improve main() function for testing by printing all supported messages and making it easy to switch devices.
Remove unnecessary null tests.
=> [orx-midi] Add pitch bend and pressure

orx-jvm/orx-gui/src/demo/kotlin/DemoXYParameter.kt, orx-jvm/orx-panel/src/main/kotlin/org/openrndr/panel/elements/XYPad.kt, orx-jvm/orx-panel/src/main/kotlin/org/openrndr/panel/style/DefaultStyles.kt
- Write label bottom-left following other UI components
- Small optimization by constructing the grid only once
then calling lineSegments() instead of lineSegment()
multiple times.
- Don't calculate textHeight
=> XYParameter tweaks to close #107

orx-triangulation/src/commonMain/kotlin/DelaunayTriangulation.kt
Index out of bounds exception when calling `hull()`
The `2 * h` is left from before refactoring by Edwin when an array was indexed where x and y coordinates of points were stored as two consecutive `Double`s in an array. Then `2 * h` gave the x-coordinate and `2 * h + 1` gave the y-coordinate. Now, an array storing `Vector2`s is used, so to retrieve the point one should index simply by `h`.
=> [orx-triangulation] Fix typo in convex hull computation

orx-noise/src/commonMain/kotlin/ShapeNoise.kt, orx-noise/src/demo/kotlin/DemoShapeNoise.kt
Achieved by testing against a smaller bounds shape (reduced by the requested distanceToEdge) to avoid false hits.
In the case of a Rectangle attempts is reduced to 1.
More noticeable the larger the distanceToEdge value is.
Add demo.
=> [orx-noise] Optimization. Reduce attempt-count in shape.uniform

.github/workflows/build.yml, .github/workflows/generate-screenshots.yml, .github/workflows/release-candidate-to-maven-central.yml, .github/workflows/release-to-maven-central.yml, README.md, build.gradle, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/org/openrndr/extra/convention/component-metadata-rule.gradle.kts, buildSrc/src/main/kotlin/org/openrndr/extra/convention/kotlin-jvm.gradle.kts, buildSrc/src/main/kotlin/org/openrndr/extra/convention/kotlin-multiplatform.gradle.kts, gradle/libs.versions.toml
Replace `fromResolutionOf("default")` with `fromResolutionResult()` for publishing jvm packages as "default" will not be a resolvable configuration in Gradle 8.0.
Remove custom dependency resolution strategy for openrndr and use a rich version range.
Fix small formatting and deprecated API usages in build scripts.
Update README with the new local maven usage and remove inaccurate info.
=> Use rich version range for openrndr

buildSrc/src/main/kotlin/CollectScreenShots.kt
CI currently seems to be failing because the collectScreenshots task's `runtimeDependencies` property isn't serializable. Marking it as `@InputFiles` seems to make Gradle understand how to serialize it.
=> Fix screenshots task on Gradle 8.0

buildSrc/src/main/kotlin/org/openrndr/extra/convention/kotlin-multiplatform.gradle.kts
Current usage of `fromResolutionOf("commonMainApiDependenciesMetadata")` we use for version mapping dependencies before publishing only works as long as we don't have openrndr dependencies in jvmMain or jsMain blocks. This PR fixes that so dependency versions are always resolved correctly for all of our openrndr dependencies.
=> Fix publishing dependency version mapping

orx-jumpflood/README.md
With the previous approach both demos recreate the filter on every animation frame,
and output log messages on the console.
=> [orx-jumpflood] fix readme examples (use filter)

orx-mesh-generators/src/commonMain/kotlin/Extrusion.kt, orx-mesh-generators/src/commonMain/kotlin/ExtrusionMorphed.kt, orx-mesh-generators/src/commonMain/kotlin/ExtrusionScaled.kt, orx-mesh-generators/src/commonMain/kotlin/Helpers.kt, orx-mesh-generators/src/commonMain/kotlin/Segment.kt, orx-mesh-generators/src/jvmDemo/kotlin/DemoExtrude05.kt, orx-mesh-generators/src/jvmDemo/kotlin/DemoExtrude06.kt
Some code I've been using, including a new method to generate extrusion with a cross-section function which allows to have a varying cross section. Accepts cross sections of different vertex counts. It does not yet use tolerance arguments, which might be desired.
Generates meshes with UV coordinates for texturing.
I changed some methods to take lists of Vector2 instead of Vector3. I'm not sure this is wanted but it was easier while playing with it. The change might require adjustments for anyone who used those methods already.
=> Orx mesh new extrusion types

orx-triangulation/src/commonTest/kotlin/TestDelaunay.kt, orx-triangulation/src/commonTest/kotlin/TestVoronoi.kt, orx-triangulation/src/commonTest/kotlin/TestVoronoiDiagram.kt, orx-triangulation/src/jvmDemo/kotlin/DemoDelaunay01.kt, orx-triangulation/src/jvmDemo/kotlin/DemoDelaunay02.kt, orx-triangulation/src/jvmDemo/kotlin/DemoVoronoi03.kt
Needs https://github.com/openrndr/openrndr/pull/388
=> Remove .take() from demos and tests when using .sampleEquidistant()

README.md
Also link to the detailed wiki page
=> [README] Don't mention specific snapshot versions

.gitignore
It seems that this folder started to be created during the build/run only recently, maybe after the update to gradle/kotlin 2.0? On my system it contains:
* 3.3.3+5
* x64
* libglfw.so
* libjemalloc.so
* liblwjgl.so
* liblwjgl_opengl.so
* liblwjgl_stb.so
=> .gitignore add /.lwjgl folder

orx-obj-loader/src/jvmMain/kotlin/OBJSaver.kt
=> [orx-obj-loader] skip padding when saving obj

openrndr-demos/build.gradle.kts, openrndr-demos/src/demo/kotlin/DemoComputeStyle01.kt, openrndr-demos/src/demo/kotlin/DemoComputeStyle02.kt, openrndr-demos/src/demo/kotlin/DemoComputeStyle03.kt, openrndr-demos/src/demo/kotlin/DemoComputeStyle04.kt, openrndr-demos/src/demo/kotlin/DemoComputeStyle05.kt, openrndr-demos/src/demo/kotlin/DemoComputeStyle06.kt, openrndr-demos/src/demo/kotlin/DemoComputeStyle07.kt, openrndr-demos/src/demo/kotlin/DemoComputeStyle08.kt, openrndr-demos/src/demo/kotlin/DemoComputeStyle09.kt, openrndr-demos/src/demo/kotlin/DemoComputeStyle10.kt, openrndr-demos/src/demo/kotlin/DemoComputeStyle20.kt
Adding 11 computeStyle demos. Demos 1 to 10 are written sequentially and make sense one after the other. The last demo is actually older and I will either change it so it makes sense in this sequence (to introduce a new concept after demo 10), or maybe remove it and add something more interesting.
=> Add computeStyle demos
