orx-camera/src/main/kotlin/Debug3D.kt, orx-camera/src/main/kotlin/OrbitalControls.kt
@edwinRNDR can you check if this is the correct implementation
=> userInteraction boolean for orx-camera

orx-fx/src/main/kotlin/color/Bloom.kt, orx-fx/src/main/resources/org/openrndr/extra/fx/gl3/color/bloom.frag
@edwinRNDR With the `ApproximateGaussianBlur` I notice that the blur is increasing in the `x` direction and not in the `y` direction. Could you please check that on your side?
=> Add Bloom effect

orx-compositor/README.md, orx-compositor/build.gradle, orx-compositor/src/main/kotlin/Compositor.kt
=> Add mask method to compositor

orx-mesh-generators/README.md
Without these examples I was lost wondering how do I draw the created meshes.
=> readme: add display 3D mesh examples

orx-mesh-generators/src/main/kotlin/Dodecahedron.kt
=> Add Dodecahedron.kt

orx-midi/src/main/kotlin/MidiTransceiver.kt
Without this the process hangs upon exit
=> Destroy midi on quit

orx-gui/README.md
Add missing Parameter types to the GUI example
=> More gui examples

orx-noise/src/main/kotlin/CubicNoise2D.kt, orx-noise/src/main/kotlin/CubicNoise3D.kt, orx-noise/src/main/kotlin/Fractal.kt, orx-noise/src/main/kotlin/PerlinNoise2D.kt, orx-noise/src/main/kotlin/PerlinNoise3D.kt, orx-noise/src/main/kotlin/Random.kt, orx-noise/src/main/kotlin/SimplexNoise2D.kt, orx-noise/src/main/kotlin/SimplexNoise3D.kt, orx-noise/src/main/kotlin/SimplexNoise4D.kt, orx-noise/src/main/kotlin/ValueNoise2D.kt, orx-noise/src/main/kotlin/ValueNoise3D.kt, orx-noise/src/test/kotlin/TestVectorShortcutFunctions.kt
Does the readme need to include examples using vectors?
=> Add vector based noise functions

orx-gui/README.md
Arguments were placed in wrong functions, arguments must be compile time constants.
=> Fix uncompilable readme example

orx-dnk3/src/main/kotlin/Scene.kt, orx-dnk3/src/main/kotlin/gltf/Gltf.kt, orx-dnk3/src/main/kotlin/gltf/GltfScene.kt
Loading the gilt scene name & propagate upwards
=> Added name property to the GLTF loader & SceneNode

orx-fx/src/main/kotlin/color/Pal.kt, orx-fx/src/main/resources/org/openrndr/extra/fx/gl3/color/pal.frag
This adds a PAL/TV effect, simulating the look of old television screens in org.openrndr.extra.fx.color.Pal.
=> Added PAL TV effect to emulate old CRT televisions.

orx-gui/src/demo/kotlin/DemoPresets01.kt, orx-gui/src/main/kotlin/Gui.kt
Split .loadParameters() .saveParameters() in two
This allows the user to read / write the gui state and
serialize it externally.
Fixes #125
=> Gui: add .toObject() .fromObject()

orx-midi/README.md, orx-midi/src/main/kotlin/MidiEvent.kt, orx-midi/src/main/kotlin/MidiTransceiver.kt
I needed to receive `program change` messages so I did a simple implementation with a bit of help from the chat on slack :)
=> program change support

orx-palette/src/main/kotlin/PaletteStudio.kt
`randomize` should also change the background/foreground colors
=> [orx-palette] Allow background to be randomized

orx-shade-styles/src/demo/kotlin/DemoAllGradients01.kt, orx-shade-styles/src/demo/kotlin/DemoNPointGradient01.kt, orx-shade-styles/src/demo/kotlin/DemoNPointLinearGradient01.kt, orx-shade-styles/src/demo/kotlin/DemoNPointRadialGradient01.kt, orx-shade-styles/src/main/kotlin/LinearGradient.kt, orx-shade-styles/src/main/kotlin/NPointGradient.kt, orx-shade-styles/src/main/kotlin/NPointLinearGradient.kt, orx-shade-styles/src/main/kotlin/NPointRadialGradient.kt
Make use of _SIZE shader defines and implement NPointLinearGradient + NPointRadialGradient
=> More n-point gradients

orx-noise/src/main/kotlin/UniformRandom.kt
Also add Int.uniform and IntVector2.uniform
=> UniformRandom: implement Rectangle argument

orx-noise/src/main/kotlin/Random.kt
=> Revert "[orx-noise] Add unseeded method to Random"

orx-panel/src/main/kotlin/org/openrndr/panel/elements/XYPad.kt
I realized I was using this .round() in my program and it was using an unnecessary loop.
=> replace repeat() with pow()

updateChangesTxt
Script to produce a change log since the last release (use before the actual release, otherwise there's no changes since the last release :-)
=> Add updateChangesTxt script

orx-jvm/orx-gui/src/main/kotlin/Gui.kt
This adds code such that clicking on "Randomize" in orx-gui, the XY, Vector2/3/4 parameters are also randomized. This is done simply by randomizing each component of the vector separately.
=> [orx-gui] Functionality for randomizing vectors

orx-shade-styles/src/demo/kotlin/DemoLinearGradient.kt
Trying to fix screenshot generation
=> Fix wrong import

buildSrc/src/main/kotlin/CollectScreenShots.kt
In produced demo-image-URL in README.md
=> Minor change to CollectScreenShots.kt

orx-quadtree/src/main/kotlin/IQuadtree.kt, orx-quadtree/src/main/kotlin/Quadtree.kt, orx-quadtree/src/main/kotlin/ReadwriteQuadtree.kt
Cherry-picks 3993085197ac11c530dec3e38f531eecb73982dc from master
=> Add quadtree nearestToPoint, and Readwrite locking (#217)

orx-color/src/commonMain/kotlin/spaces/ColorOKLABa.kt, orx-shade-styles/src/commonMain/kotlin/NPointLinearGradient.kt, orx-shade-styles/src/commonMain/kotlin/RadialGradient.kt, orx-shade-styles/src/demo/kotlin/DemoNPointLinearGradient01.kt
in RadialGradient.kt and NPointLinearGradient.kt
Add OKLab variation to DemoNPointLinearGradient.kt
Mention OKLab (l, a, b) ranges and meaning.
=> OKLab color gradients were partially implemented

orx-shapes/src/commonMain/kotlin/RectangleGrid.kt, orx-shapes/src/demo/kotlin/DemoRectangleGrid01.kt, orx-shapes/src/demo/kotlin/DemoRectangleGrid02.kt
I tested that calling .grid with row and column counts between 0 and 20 (400 combinations) return the expected number of cells.
=> Add new `Rectangle.grid` with cell size argument

orx-kdtree/src/demo/kotlin/DemoKNearestNeighbour01.kt, orx-kdtree/src/main/kotlin/KDTree.kt
I also removed excessive imports
=> KDTree: tree build time no longer reported, as it can be measured externally if needed

orx-easing/README.md, orx-easing/build.gradle.kts, orx-easing/src/commonMain/kotlin/Easing.kt, orx-easing/src/demo/kotlin/DemoEasings01.kt
Add animation, text labels, design to demo
=> Fix easeInOutQuintic, tweak demo

orx-compositor/src/commonMain/kotlin/Compositor.kt
This was accidentally removed in #236.
=> [orx-compositor] Reintroduce accumulation variable

orx-jvm/orx-gui/src/main/kotlin/Gui.kt, orx-jvm/orx-panel/src/main/kotlin/org/openrndr/panel/ControlManager.kt
Otherwise the usage is ambiguous with the recently introduced Display in openrndr-application.
=> Add explicit Display import

orx-color/src/commonMain/kotlin/presets/Colors.kt, orx-color/src/commonMain/kotlin/spaces/ColorHPLUVa.kt, orx-color/src/commonMain/kotlin/spaces/ColorHSLUVa.kt, orx-color/src/commonMain/kotlin/spaces/ColorOKHSL.kt, orx-color/src/commonMain/kotlin/spaces/ColorOKHSV.kt, orx-color/src/commonMain/kotlin/spaces/ColorOKLABa.kt, orx-color/src/commonMain/kotlin/spaces/ColorOKLCHa.kt, orx-color/src/commonMain/kotlin/spaces/ColorXSLUVa.kt, orx-jvm/orx-gui/src/main/kotlin/Gui.kt, orx-jvm/orx-keyframer/src/main/kotlin/Keyframer.kt, orx-jvm/orx-rabbit-control/src/main/kotlin/RabbitControlServer.kt
This PR applies similar changes as in openrndr/openrndr#326 to be compatible with openrndr.
=> Color model changes

orx-mesh-generators/build.gradle, orx-mesh-generators/src/demo/kotlin/DemoAll.kt, orx-mesh-generators/src/demo/kotlin/DemoBox.kt, orx-mesh-generators/src/main/kotlin/Cap.kt, orx-mesh-generators/src/main/kotlin/GeneratorBuffer.kt
Add demo with all available meshes rotating
=> Add resolveMesh(), capMesh(), comments

orx-image-fit/README.md, orx-image-fit/build.gradle.kts, orx-image-fit/src/commonMain/kotlin/ImageFit.kt, orx-image-fit/src/demo/kotlin/DemoImageFit01.kt
Simplify code.
Add demo of all FitMethod and alignments.
Add comments.
=> Add Rectangle.fit(Rectangle):Matrix44, FitMethod.Fill, FitMethod.None

buildSrc/src/main/kotlin/org/openrndr/extra/convention/FFmpegRule.kt, buildSrc/src/main/kotlin/org/openrndr/extra/convention/LwjglRule.kt, buildSrc/src/main/kotlin/org/openrndr/extra/convention/Utils.kt, buildSrc/src/main/kotlin/org/openrndr/extra/convention/kotlin-jvm.gradle.kts, buildSrc/src/main/kotlin/org/openrndr/extra/convention/kotlin-multiplatform.gradle.kts
It needs to be verified whether this fix is actually necessary. This can be done by building the project on Linux/MacOS with ARM64 architecture.
=> Change arm64 to aarch64

orx-property-watchers/README.md
=> Fix README.md so the description is picked up in the root README.md

orx-view-box/src/commonMain/kotlin/ViewBox.kt
Requires https://github.com/openrndr/openrndr/pull/367
=> Remove pressedButtons, now implemented via MouseTracker

openrndr-demos/build.gradle.kts, openrndr-demos/src/demo/kotlin/DemoCatmullRom01.kt, orx-fx/build.gradle.kts, orx-jumpflood/build.gradle.kts, orx-noise/build.gradle.kts, orx-shader-phrases/build.gradle.kts
=> Fix gradle deprecation warnings

.github/workflows/build.yml, .github/workflows/generate-screenshots.yml, .github/workflows/release-candidate-to-maven-central.yml, .github/workflows/release-to-maven-central.yml, orx-shapes/src/jvmDemo/kotlin/text/DemoText01.kt
When running the actions it complains about
deprecated node.js
Next commits will update other actions.
=> Update GitHub actions

gradle/libs.versions.toml, orx-color/src/commonTest/kotlin/mixing/TestSpectral.kt, orx-expression-evaluator-typed/build.gradle.kts, orx-expression-evaluator-typed/src/jvmTest/kotlin/typed/TestListLiteralExpression.kt, orx-expression-evaluator-typed/src/jvmTest/kotlin/typed/TestTypedCompiledExpression.kt, orx-expression-evaluator/build.gradle.kts, orx-expression-evaluator/src/jvmTest/kotlin/TestCompiledExpression.kt, orx-expression-evaluator/src/jvmTest/kotlin/TestCompiledFunctions.kt, orx-expression-evaluator/src/jvmTest/kotlin/TestExpressionDelegates.kt, orx-expression-evaluator/src/jvmTest/kotlin/TestExpressionErrors.kt, orx-expression-evaluator/src/jvmTest/kotlin/TestExpressions.kt, orx-expression-evaluator/src/jvmTest/kotlin/TestOperators.kt, orx-jvm/orx-keyframer/build.gradle.kts, orx-jvm/orx-keyframer/src/test/kotlin/TestKeyframerChannel.kt, orx-jvm/orx-keyframer/src/test/kotlin/TestKeyframerErrors.kt, orx-jvm/orx-kotlin-parser/build.gradle.kts, orx-jvm/orx-olive/build.gradle.kts, orx-parameters/src/jvmTest/kotlin/TestAnnotations.kt, orx-property-watchers/build.gradle.kts
Kluent is no longer maintained
=> Replace kluent with kotlin.test

orx-shapes/src/commonMain/kotlin/bezierpatches/BezierPatchDrawer.kt, orx-shapes/src/jvmDemo/kotlin/bezierpatch/DemoBezierPatch06.kt
=> [orx-shapes] BezierPatch: add missing user uniforms, demo
